### ISSUE TITLE
PHP Fatal Error in "Calc.php"

### ISSUE THREAD

**Issue by agaleski** [woocommerce/woocommerce-gateway-klarna#107]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior
Loading Part Payments on Checkout Page
-

### Actual behavior
Unable to choose ANY payment method and the "Place Order" button disappears due to a 500 error while AJAX request loading the payment method fields.
-

### Steps to reproduce the behavior
Install a version higher than 2.4.2 and enable part payments with Flatsome Theme.
-

### Klarna plugin version
2.5.3
-

### WordPress version
4.8.2
-

### WooCommerce version
3.1.2
-

### Klarna country
DE
-

### Error / Stack Trace
```
2017/11/16 02:26:38 [error] 1395#1395: *46078 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Invalid country {} in /wp/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Calc.php:633
Stack trace:
#0 /wp/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Calc.php(333): Klarna\XMLRPC\Calc::getLowestPaymentForAccount(NULL)
#1 /wp/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Calc.php(592): Klarna\XMLRPC\Calc::getPayArray(43.89, Object(Klarna\XMLRPC\PClass), 0)
#2 /wp/wp-content/plugins/woocommerce-gateway-klarna/views/public/payment-fields-part-payment.php(134): Klarna\XMLRPC\Calc::calcMonthlyCost(43.89, Object(Klarna\XMLRPC\PClass), 0)
#3 /wp/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-part-payment.php(572): include('/var/www/prod_n...')
```
-

### Code causing the Issue
_/wp/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Calc.php_
```
    /**
     * Returns the lowest monthly payment for Klarna Account.
     *
     * @param int $country Country constant.
     *
     * @throws Exception\KlarnaException
     *
     * @return int|float Lowest monthly payment.
     */
    public static function getLowestPaymentForAccount($country)
    {
        $country = Country::getCode($country);

        switch (strtoupper($country)) {
            case 'SE':
                return 50.0;
            case 'NO':
                return 95.0;
            case 'FI':
                return 8.95;
            case 'DK':
                return 89.0;
            case 'DE':
            case 'AT':
                return 6.95;
            case 'NL':
                return 5.0;
            default:
                throw new \RuntimeException("Invalid country {{$country}}");
        }
    }
```

Should be: `Exception\KlarnaException`
Is: `\RuntimeException`
-

**Comment by kristibarbosky** [comment]
I reviewed this issue with Neshat (from Klarna) today, who I believe is working with @agaleski regarding this issue.  Since Klarna is not currently maintaining the Klarna SDK, this SDK code would need to be customized until the SDK is maintained (but no target date for this yet) or the merchant could when reasonable (with an updated Klarna contract) update to [Klarna Payments](https://github.com/krokedil/klarna-payments-for-woocommerce) or [KCOv3](https://github.com/krokedil/klarna-checkout-for-woocommerce)

If customizing this code, Neshat shared that the value for DE should be 6.95
